# Site settings
title: Jalal's blog
author: Jalal Hejazi
#email: your-email@example.com
description: Continuous learning
baseurl: "" # the subpath of your site, e.g. /blog
url: https://jh.github.io
github_username: jalalhejazi
# Build settings
markdown: GFM
theme: minima
show_excerpts: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
gist:
  noscript: false
future: true 
jailed: false
