name: honeybees

on: push

permissions: 
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Generate public/index.html
        run: |
          mkdir public
          cat > public/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>🐝 10 Life Lessons</title>
              <style>
                /* General Reset */
                * {
                  margin: 0;
                  padding: 0;
                  box-sizing: border-box;
                }

                body {
                  font-family: Arial, sans-serif;
                  line-height: 1.6;
                  background-color: #fefbe9;
                  color: #333;
                  padding: 20px;
                }

                header {
                  background-color: #f7c948;
                  padding: 20px;
                  text-align: center;
                  border-radius: 8px;
                  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                }

                header h1 {
                  font-size: 2.5rem;
                  color: #fff;
                  margin: 0;
                }

                p {
                  margin-bottom: 20px;
                }

                pre {
                  background-color: #fff3cd;
                  padding: 20px;
                  border-left: 4px solid #f7c948;
                  border-radius: 4px;
                  font-family: "Courier New", Courier, monospace;
                  white-space: pre-wrap;
                }

                ol {
                  list-style: decimal inside;
                  margin-left: 20px;
                  padding: 0;
                }

                ol li {
                  margin-bottom: 15px;
                  background: #fff;
                  padding: 10px 15px;
                  border: 1px solid #e2e2e2;
                  border-radius: 4px;
                  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
                  transition: transform 0.2s ease-in-out;
                }

                ol li:hover {
                  transform: translateY(-5px);
                }

                a {
                  color: #f7c948;
                  text-decoration: none;
                  font-weight: bold;
                }

                a:hover {
                  text-decoration: underline;
                }

                footer {
                  margin-top: 30px;
                  text-align: center;
                  font-size: 0.9rem;
                  color: #666;
                }

                @media (max-width: 768px) {
                  body {
                    padding: 10px;
                  }

                  header h1 {
                    font-size: 2rem;
                  }

                  ol li {
                    font-size: 0.9rem;
                  }
                }
              </style>
            </head>
            <body>
              <header>
                <h1> 10 Life Lessons from Honeybees 🐝 </h1>
              </header>
              <p>
                Believe it or not, 🐝🐝🐝 honeybees have a lot to teach us about life:
              </p>

              <pre>  
                These remarkable insects are the ultimate team players, 
                working together seamlessly for the success of the hive. 
                Not only do they value every individual’s contribution, 
                but they also never lose sight of the greater good. 
                In other words, honeybees know how to lift each other up 
                while keeping the entire community thriving—and 
                we can learn a lot from that.
              </pre>

              <ol>
                <li><strong>Shared Purpose:</strong> Honeybees work together with a clear collective goal—nurturing the hive. This reminds us that when groups unite behind a shared vision, their combined efforts become more impactful.</li>
                <li><strong>Respect for Individual Roles:</strong> Every bee has a specific job, from gathering pollen to guarding the hive. Recognizing and appreciating each person’s unique contributions can strengthen a team’s overall performance.</li>
                <li><strong>Open Communication:</strong> Bees use pheromones and dances to share information about food sources. In human teams, transparent and consistent communication ensures everyone stays informed and aligned.</li>
                <li><strong>Adaptability:</strong> When resources change or weather turns harsh, bees quickly adjust their tasks. Remaining flexible and open to new approaches helps teams navigate unexpected challenges.</li>
                <li><strong>Efficiency in Effort:</strong> Honeybees never waste energy—they streamline their work to maximize productivity. Human teams can benefit from minimizing busywork and focusing on what truly matters.</li>
                <li><strong>Empathy for the Collective:</strong> Bees maintain a healthy hive environment, attending to each other’s needs. Fostering a supportive atmosphere encourages team members to help one another and grow together.</li>
                <li><strong>Constant Learning:</strong> Worker bees continually explore new areas and strategies to find better resources. Embracing a culture of learning and improvement keeps teams adaptable and innovative.</li>
                <li><strong>Trust in the System:</strong> Each bee trusts its fellow workers to fulfill their roles. When team members have faith in each other’s reliability, it builds confidence and synergy.</li>
                <li><strong>Resilience Under Pressure:</strong> Hives persevere despite predators, weather changes, and scarce resources. Teams that cultivate resilience can recover quickly from setbacks and maintain forward momentum.</li>
                <li><strong>Focus on the Greater Good:</strong> Honeybees always prioritize the hive’s well-being. Remembering that long-term success often comes from working in the interest of the whole team can guide us toward more meaningful, sustainable collaboration.</li>
              </ol>

              <footer>
                GitHub Pages with <strong>${{ github.sha }}</strong> commit ID has been deployed. 
              </footer>
            </body>
          </html>

          EOL
      -
        name: Deploy 🐝 
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}